name: islami_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  fluttertoast: ^9.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
