name: islami_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  google_fonts: ^6.3.3
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  firebase_crashlytics: ^4.3.10
  bloc: ^9.1.0
  http: ^1.6.0
  cloud_functions: ^5.6.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
